export default [
    {
        id: '1',
        categoryId: '1',
        name: 'Baked chilli & jacket potatoes',
        description: ['Heat oven to 200C/180C fan/gas 6. Prick the potatoes all over with a fork, then put on a baking sheet and bake in the oven for 1 hr.',
            'While the potatoes are baking, heat the oil in a large frying pan. Add the onion and fry over a high heat for 5 mins until softened. Add the garlic and chilli sachet. Stir a few times to coat the onions in the spices, then tip the onion mixture into a large ovenproof dish.',
            'Put the pan back over high heat and add the beef mince, breaking it up with a spatula as you go. Cook until starting to become crisp at the edges, then add to the dish with the onions. Return the pan to heat and cook the bacon until crisp at the edges. Add the bacon to the beef and stir to combine.',
            'Stir in the tomato purée and tomatoes, then put the dish in the oven with the potatoes and bake for 25-30 mins until bubbling and starting to thicken. Stir in the beans and season well. Return to the oven for 5 mins to warm through.',
            'Cut a cross in the top of each potato and squeeze the sides to open. Spoon in the baked chilli and top with soured cream, cheese and coriander if you like.'],
        videoLink: 'j02cMPySPDE',
        image: '../img/potato-1.jpg',
        author: 'Miriam Nice',
        rating: '4',
        views: '523',
        ingredients: ['4 large jacket potatoes',
            '1 tbsp sunflower oil',
            '2 red onions, chopped',
            '3 garlic cloves, crushed',
            '1 sachet (30-39g), chilli con carne seasoning mix',
            '500g beef mince',
            '100g smoked bacon lardons',
            '2 tbsp tomato purée',
            '400g can chopped tomatoes',
            '400g can black beans, drained soured cream, grated cheese and coriander leaves, to serve']
    },
    {
        id: '2',
        categoryId: '1',
        name: 'Spicy turkey sweet potatoes',
        description: ['Heat oven to 200C/180C fan/gas 6. Prick the potatoes, place on a baking tray and bake for 45 mins or until really soft.',
            'Meanwhile, heat the oil in a frying pan, add the onion and cook gently for 8 mins until softened. Stir in the garlic, then tip in the mince and stir to break up. Cook over a high heat until any liquid has evaporated and the mince is browned, about 10 mins. Pour in the passata, then fill the carton a quarter full of water and tip that in too. Add the barbecue sauce and cayenne, then lower the heat and simmer gently for 15 mins, adding a little extra water if needed. Taste and season.',
            'When the potatoes are soft, split them down the centre and spoon the mince over the top. Add a dollop of soured cream and a sprinkling of chives.'],
        videoLink: 'bUpN6Tlzt3U',
        image: '../img/potato-2.jpg',
        author: 'Emily Kydd',
        rating: '5',
        views: '754',
        ingredients: ['4 sweet potatoes',
            '1 tbsp olive oil',
            '1 onion, finely chopped',
            '1 garlic clove, crushed',
            '500g pack turkey thigh mince',
            '500g carton passata',
            '3 tbsp barbecue sauce',
            '½ tsp cayenne pepper',
            '4 tbsp soured cream',
            '½ pack chives, finely snipped']
    },
    {
        id: '3',
        categoryId: '1',
        name: 'Pizza baked potato',
        description: ['Heat oven to 200C/180C fan/gas 6. Scrub the potatoes and dry well, then prick several times with a fork. Bake directly on the oven shelf for 1-1½ hrs, until they feel soft. If you are short of time, prick each potato with a fork, wrap in a sheet of kitchen paper and microwave on High for 8-10 mins until soft inside.',
            'While the potatoes cook, heat the oil in a small pan and sauté the onion for 5 mins to soften. Stir in the garlic and pepperoni, and cook for 1-2 mins, then add the chopped tomatoes. Bring to the boil, then simmer for 5 mins. Season and stir in half the basil. Spoon over the split potatoes and top each one with a good handful of cheese and the rest of the basil.'],
        videoLink: 'ANYZdHu8jHg',
        image: '../img/potato-3.jpg',
        author: 'Katy Greenwood',
        rating: '4',
        views: '723',
        ingredients: ['4 baking potatoes',
            '1 tbsp olive oil',
            '½ red onion, finely chopped',
            '1 garlic clove, crushed',
            '60g pack sliced pepperoni, torn',
            '400g can chopped tomato',
            '½ small pack basil leaves, shredded',
            '100g grated mozzarella',]
    },
    {
        id: '4',
        categoryId: '1',
        name: 'Baked potatoes with spicy dhal',
        description: ['Heat oven to 200C/180C fan/gas 6. Put the potatoes in the oven and bake for 1 hr until tender and the skin is crispy.',

            'While they are baking, make the dhal. Heat the oil in a medium pan and fry the spices to release their flavours. As soon as they start to crackle, tip in the onion, garlic and chilli, with a splash of water to stop the spices from burning. Cook for 5 mins until the onion softens.',

            'Add the lentils, tomato and stock, then cover and cook for 10 mins. Tip in the chickpeas, cover and cook for 10 mins more until the lentils are tender. Season to taste, stir in the coriander and spoon onto the jacket potatoes. Serve with chutney or lime pickle.'],
        videoLink: 'OF6-fRCAFBQ',
        image: '../img/potato-4.jpg',
        author: 'Sara Buenfeld',
        rating: '4',
        views: '452',
        ingredients: ['2 baking potatoes (Vivaldi have a lovely, creamy texture)',
            '1 tbsp sunflower oil',
            '½ tsp cumin seed',
            '½ tsp black mustard seeds',
            '½ tsp turmeric',
            '1 onion, thinly sliced',
            '3 garlic cloves, sliced',
            '1 red chilli, deseeded and sliced',
            '85g red lentil',
            '1 tomato, chopped',
            '400ml vegetable stock',
            '210g can chickpea, drained',
            'good handful chopped coriander',
            'chutney or lime pickle, to serve']
    },
    {
        id: '5',
        categoryId: '1',
        name: 'Classic jacket potatoes',
        description: ['Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın. Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.',
            'Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin. Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin. Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçapı ilave edin. Kapağını kapatarak 4-5dk kadar pişmeye bırakın. Suyunu çektikten sonra bezelye ve patlıcanı ilave edin. Baharatları da ekleyerek 3-4dk daha pişirin. Tavuklar da artık pişmiş olmalılar.'],
        videoLink: 'b8UrXs3-oXs',
        image: '../img/potato-5.jpg',
        author: 'Good Food',
        rating: '5',
        views: '856',
        ingredients: ['4 large baking potatoes',
            '2 tsp olive oil',
            '200ml soured cream']
    },
    {
        id: '6',
        categoryId: '2',
        name: 'Mexican chicken burger',
        description: ['Put the chicken breast between two pieces of cling film and bash with a rolling pin or pan to about 1cm thick. Mix the chipotle paste with half the lime juice and spread over the chicken.',

            'Heat a griddle pan over a high heat. Once hot, cook the chicken for 3 mins each side until cooked through, adding the cheese for the final 2 mins of cooking. Add the bun, cut-side down, to the griddle pan to toast lightly. Season the chicken.',

            'Meanwhile, mash the avocado with the remaining lime juice. Stir in the cherry tomatoes, jalapeño and garlic, and season with a little salt. Spread over the base of the bun, then add the chicken followed by the top of the bun.'],
        videoLink: 't2W2MkBmi3w',
        image: '../img/burger-1.jpg',
        author: 'Katy Greenwood',
        rating: '5',
        views: '234',
        ingredients: ['1 chicken breast',
            '1 tsp chipotle paste',
            '1 lime, juiced',
            '1-2 slices cheese',
            '1 brioche bun, split',
            '½ avocado',
            '2 cherry tomatoes, chopped',
            '3-4 pickled jalapeño slices, chopped',
            '½ small garlic clove, finely grated']
    },
    {
        id: '7',
        categoryId: '2',
        name: 'Green burgers',
        description: ['Heat half the oil in a frying pan and gently fry the onions for about 10 mins until pale and soft, then leave to cool a little.',

            'Finely chop the spinach in a food processor and tip into a bowl. Add the cooled onion, breadcrumbs, nutmeg, cheddar and Parmesan, and mash together. Add the beaten egg, a little at a time (you may not need all of it), until the mixture holds together. Divide into eight (see tip below) and shape into fat burgers.',

            'Put the flour in a shallow bowl, season well and dip the burgers into the flour to coat. Store in a plastic container between layers of baking parchment. Either chill until ready to cook, or freeze.',

            'Heat the remaining oil in the frying pan and fry for about 5 mins each side until browned all over. Serve in the crusty rolls, with a couple of slices of tomato, ketchup and sweet potato fries on the side, if you like.'],
        videoLink: 'Vx8lCSrcmQY',
        image: '../img/burger-2.jpg',
        author: 'Amanda Grant',
        rating: '5',
        views: '824',
        ingredients: ['2 tbsp olive oil',
            '2 onions, finely chopped',
            '250g bag spinach',
            '5 slices white bread, blitzed into breadcrumbs (or 150g dried breadcrumbs)',
            'good grating of fresh nutmeg',
            '100g mature cheddar, grated',
            '40g parmesan, finely grated',
            '1-2 large eggs, beaten',
            '3 tbsp plain flour']
    },
    {
        id: '8',
        categoryId: '2',
        name: 'Miso burgers with mint & pomegranate slaw',
        description: ['Heat oven to 220C/200C fan/gas 7. Cook the bulghar in a small pan of water for 5 mins. Meanwhile, heat the oil in a large non-stick frying pan and fry the onions and garlic, stirring, for 5 mins or until starting to turn golden. Add the carrots and chilli, and cook, stirring frequently, for 5 mins until the carrots soften. Add the cumin, ground coriander, coriander stalks and lime zest, and stir well.',
            'Tip the chickpeas into a bowl and crush with a masher or fork, then add the eggs and miso to form a chunky paste.',
            'Drain the bulghar well and stir into the spicy vegetables. Take off the heat, shape into eight burgers and place on a baking sheet lined with baking parchment. Bake in the oven for 15-20 mins or until firm and starting to turn golden.',
            'For the slaw, combine all the ingredients in a big bowl with the lime juice and coriander leaves. Serve with the burgers and lime wedges for squeezing over.'],
        videoLink: 'RMcoHFrb9KI',
        image: '../img/burger-3.jpg',
        author: 'Katy Greenwood',
        rating: '5',
        views: '532',
        ingredients: ['75g bulghar wheat',
            '1 tbsp rapeseed oil',
            '2 onions, chopped',
            '4 garlic cloves, chopped',
            '2 carrots, coarsely grated',
            '1 large red chilli, deseeded and finely chopped',
            '1 tsp cumin seeds',
            '1 tbsp ground coriander',
            '30g pack coriander, stalks and leaves chopped but kept separate',
            '1 lime, zested, ½ juiced, ½ cut into 4 wedges',
            '2 x 400g cans chickpeas, drained',
            '2 large eggs',
            '2 tbsp white miso paste']
    },
    {
        id: '9',
        categoryId: '2',
        name: 'Prawn & salmon burgers with spicy mayo',
        description: ['Briefly blitz half the prawns, half the salmon, the spring onions, lemon zest and half the coriander in a food processor until it forms a coarse paste. Tip into a bowl, stir in the rest of the prawns and salmon, season well and shape into four burgers. Chill for 10 mins.',

            'Mix the mayo and chilli sauce together in a small bowl, season and add some lemon juice to taste. Mix the lettuce with the cucumber, dress with a little of the remaining lemon juice and 1 tsp olive oil, then set aside.',

            'Heat the remaining oil in a large frying pan and fry the burgers for 3-4 mins each side or until they have a nice crust and the fish is cooked through. Serve with the salad on the side or in toasted burger buns, if you like, with a good dollop of the spicy mayo.'],
        videoLink: 'Q9FbiGrKesQ',
        image: '../img/burger-4.jpg',
        author: 'Elena Silcock',
        rating: '5',
        views: '645',
        ingredients: ['180g pack peeled raw prawns, roughly chopped',
            '4 skinless salmon fillets, chopped into small chunks',
            '3 spring onions, roughly chopped',
            '1 lemon, zested and juiced',
            'small pack coriander',
            '60g mayonnaise or Greek yogurt',
            '4 tsp chilli sauce (we used sriracha)',
            '2 Little Gem lettuces, shredded',
            '1 cucumber, peeled into ribbons',
            '1 tbsp olive oil',
            '4 seeded burger buns, toasted, to serve']
    },
    {
        id: '10',
        categoryId: '2',
        name: 'Bhaji burger',
        description: ['First, make the burgers. Tip all the ingredients into a bowl with a good pinch of salt and squeeze together with your fingers. Shape into three patties and chill in the fridge.',

            'For the raita, grate the cucumber and squeeze out as much liquid as you can. Put in a bowl with the yogurt, mint and some salt. Mix and chill.',

            'For the bhajis, tip the flour, spices and bicarb into a bowl with a pinch of salt. Slowly add 200ml cold water to make a thick batter (you might not need all of it), then mix in the onion.',

            'Heat the oil in a large frying pan. Add the batter in batches so you have three burger-sized bhajis. Sizzle for 3 mins until crispy on one side, then flip and cook on the other side until cooked through. Keep warm.',

            'Barbecue, griddle or pan-fry the burgers to your liking. Put lettuce and a burger on each bun and top with some raita, a bhaji and red onion. Serve the mango chutney on the side.'],
        videoLink: 'S9orBS8IfAM',
        image: '../img/burger-5.jpg',
        author: 'Barney Desmazery',
        rating: '5',
        views: '199',
        ingredients: [
            '400g lamb mince',
            '2 tbsp tandoori paste',
            '1 tsp cumin seeds',
            '½ cucumber',
            '150g pot plain yogurt',
            '½ small pack mint, leaves chopped',
            '100g plain flour',
            '1 tbsp garam masala',
            '1 tsp bicarbonate of soda',
            '1 onion, halved and finely sliced',
            '3 tbsp sunflower oil',
            '3 burger buns (we used brioche buns), toasted',
            'a few lettuce leaves',
            'red onion, thinly sliced',
            'mango chutney']
    },
    {
        id: '11',
        categoryId: '3',
        name: 'Raw strawberry jam',
        description: ['Blend 3/4 fruit and roughly chop the rest. Add the rest of the ingredients mix well and leave for 1 hr, stirring occasionally, until thickened. Store in a sterilised jar in the fridge for up to 4 days or freeze for up to 1 month.'],
        videoLink: '7A0obDE8PbA',
        image: '../img/jam-1.jpg',
        author: 'Miriam Nice',
        rating: '4',
        views: '641',
        ingredients: ['400g strawberries, hulled',
            '2 tbsp lemon juice',
            '2 tbsp maple syrup',
            '2 tbsp chia seeds']
    },
    {
        id: '12',
        categoryId: '3',
        name: 'Gooseberry & elderflower jam',
        description: ['Tip the gooseberries into a large saucepan or preserving pan with 300ml water. Cook over a low heat for about 15 mins, stirring occasionally, until the fruit has broken down into a soupy purée.',

            'Add the sugar and cook over a low heat until the sugar has dissolved, then turn up the heat as high as it will go and boil everything for 10 mins, stirring the bottom to make sure the jam doesn’t burn and skimming any scum off when it appears. If you have a jam or digital thermometer, the optimum temperature for the jam to set is 105C, but anything around 104C will be fine.',
            'Do the wrinkle test (see tip) on a frozen saucer to make sure it’s set, then add the elderflower cordial and leave to cool before decanting your jam into sterilised jars.'],
        videoLink: 'zosJ7t-1PUM',
        image: '../img/jam-2.jpg',
        author: 'Barney Desmazery',
        rating: '4',
        views: '430',
        ingredients: ['1kg gooseberries',
            '900g granulated white sugar',
            '100ml elderflower cordial']
    },
    {
        id: '13',
        categoryId: '3',
        name: 'Cinnamon-scented plum jam',
        description: ['Sterilise the jars and any other equipment before you start (see tip). Put a couple of saucers in the freezer, as you’ll need these for testing whether the jam is ready later (or use a sugar thermometer). Put the plums in a preserving pan and add 200ml water. Bring to a simmer, and cook for about 10 mins until the plums are tender but not falling apart. Add the sugar, ground cinnamon and lemon juice, then let the sugar dissolve slowly, without boiling. This will take about 10 mins.',

            'Increase the heat and bring the jam to a full rolling boil. After about 5 mins, spoon a little jam onto a cold saucer. Wait a few seconds, then push the jam with your fingertip. If it wrinkles, the jam is ready. If not, cook for a few mins more and test again, with another cold saucer. If you have a sugar thermometer, it will read 105C when ready.',

            'Take the jam off the heat and add the cinnamon sticks (if using) and the knob of butter. The cinnamon will look pretty in the jars and the butter will disperse any scum. Let the jam cool for 15 mins, which will prevent the lumps of fruit sinking to the bottom of the jars. Ladle into hot jars, seal and leave to cool. Will keep for 1 year in a cool, dark place. Chill once opened.'],
        videoLink: '5IoF4GIR-7g',
        image: '../img/jam-3.jpg',
        author: 'Jane Hornby',
        rating: '4',
        views: '319',
        ingredients: ['2kg plums, stoned and roughly chopped',
            '2kg white granulated sugar',
            '2 tsp ground cinnamon',
            '1 tbsp lemon juice',
            '3 cinnamon sticks (optional)',
            'knob of butter']
    },
    {
        id: '14',
        categoryId: '3',
        name: 'Rhubarb & vanilla jam',
        description: ['Put a small plate in the freezer. Put the rhubarb into a preserving pan or your largest saucepan with the sugar and halved vanilla pods. Heat gently, stirring, until all the sugar has dissolved, then squeeze in the lemon juice and increase the heat.',

            'Boil for about 10 mins, skimming off the scum as you go (the fruit should be soft). Test for setting point by spooning a little onto your chilled plate. After 1-2 mins, push your finger through the jam – if the surface wrinkles it is ready, if not, keep cooking for 2-min intervals, testing in between. (Or if you have a sugar thermometer it should reach 105C)',

            'Once the jam is ready, let it cool for about 15 mins before ladling into warm sterilised jars and sealing. Will keep for 6 months in a cool, dark place.'

        ],
        videoLink: 'AXwS-PNlo-Y',
        image: '../img/jam-4.jpg',
        author: 'Sarah Cook',
        rating: '5',
        views: '831',
        ingredients: ['1kg rhubarb, weighed after trimming, cut into 3cm chunks',
            '1kg jam sugar(or 1kg caster sugar plus 1 x 8g sachet pectin - we used Tate & Lyle)',
            '2 vanilla pods, halved lengthways',
            'juice 1 lemon']
    },
    {
        id: '15',
        categoryId: '3',
        name: 'Strawberry jam',
        description: ['Wash, drain and hull the fruit and put in a large non-metallic bowl. Sprinkle over the lemon juice and sugar, gently mix. Cover with a tea towel and leave overnight. (This helps keep the strawberries whole.)',

            'Put a saucer in the freezer. Tip the fruit and juice into a preserving pan or a 4.5 litre/8 pint heavybased pan. Heat gently, stirring, to dissolve the sugar. Do not boil until it has.',

            'Turn up the heat, then boil hard for exactly 4 minutes (use a timer). Take off the heat to test for setting point. Spoon a little jam onto the cold saucer. After a couple of minutes gently push your finger through the jam and if the surface wrinkles it is ready. If not, return to the boil for 2 minutes, then re-test.',

            'Take off the heat and swirl in the butter. If the scum doesn’t dissolve, skim with a slotted spoon. Cool for 10-15 minutes. (Pot when too hot and all the fruit rises to the top.)',

            'Stir gently to distribute the fruit, then pour into warm sterilised jars. Put waxed discs on straight away, cover with lids or cellophane circles, then seal, label and wipe the jars. Keeps for 6 months in a cool dry cupboard.'],
        videoLink: '7A0obDE8PbA',
        image: '../img/jam-5.jpg',
        author: 'Mary Cadogan',
        rating: '5',
        views: '511',
        ingredients: ['1.8kg small whole strawberries',
            'juice of 3 lemons',
            '1.84kg jam sugar (not to be confused with preserving sugar)',
            'knob of butter']
    },
    {
        id: '16',
        categoryId: '4',
        name: 'Pizza Margherita',
        description: ['Make the base: Put the flour into a large bowl, then stir in the yeast and salt. Make a well, pour in 200ml warm water and the olive oil and bring together with a wooden spoon until you have a soft, fairly wet dough. Turn onto a lightly floured surface and knead for 5 mins until smooth. Cover with a tea towel and set aside. You can leave the dough to rise if you like, but it’s not essential for a thin crust.',

            'Make the sauce: Mix the passata, basil and crushed garlic together, then season to taste. Leave to stand at room temperature while you get on with shaping the base.',

            'Roll out the dough: If you’ve let the dough rise, give it a quick knead, then split into two balls. On a floured surface, roll out the dough into large rounds, about 25cm across, using a rolling pin. The dough needs to be very thin as it will rise in the oven. Lift the rounds onto two floured baking sheets.',

            'Top and bake: Heat oven to 240C/fan 220C /gas 8. Put another baking sheet or an upturned baking tray in the oven on the top shelf. Smooth sauce over bases with the back of a spoon. Scatter with cheese and tomatoes, drizzle with olive oil and season. Put one pizza, still on its baking sheet, on top of the preheated sheet or tray. Bake for 8-10 mins until crisp. Serve with a little more olive oil, and basil leaves if using. Repeat step for remaining pizza.'],
        videoLink: 'az5D8C6K5Dk',
        image: '../img/pizza-1.jpg',
        author: 'Good Food',
        rating: '5',
        views: '841',
        ingredients: ['300g strong bread flour',
            '1 tsp instant yeast (from a sachet or a tub)',
            '1 tsp salt',
            '1 tbsp olive oil, plus extra for drizzling',
            '100ml passata',
            'handful fresh basil or 1 tsp dried',
            '1 garlic clove, crushed',
            '125g ball mozzarella, sliced',
            'handful grated or shaved parmesan (or vegetarian alternative)',
            'handful cherry tomatoes, halved']
    },
    {
        id: '17',
        categoryId: '4',
        name: 'Superhealthy pizza',
        description: ['Mix the flours and yeast with a pinch of salt in a food processor fitted with a dough blade. Pour in the water and mix to a soft dough, then work for 1 min. Remove the dough and roll out on a lightly floured surface to a round about 30cm across. Lift onto an oiled baking sheet.',

            'Spread the canned tomatoes over the dough to within 2cm of the edges. Arrange the cherry tomatoes and courgettes over the top, then scatter with the mozzarella. Mix the capers, olives and garlic, then scatter over the top. Drizzle evenly with the oil. Leave to rise for 20 mins. Heat oven to 240C/ fan 220C/gas 9 or the highest setting.',

            'Bake the pizza for 10-12 mins until crisp and golden around the edges. Scatter with the parsley to serve.'],
        videoLink: 'micSeBbPJxo',
        image: '../img/pizza-2.jpg',
        author: 'Mary Cadogan',
        rating: '4',
        views: '942',
        ingredients: ['100g each strong white and strong wholewheat flour',

            '1 tsp or 7g sachet easy-blend dried yeast',

            '125ml warm water',

            '200g can chopped tomato, juice drained',
            'handful cherry tomatoes, halved',
            '1 large courgette, thinly sliced using a peeler',
            '25g mozzarella, torn into pieces',
            '1 tsp capers in brine, drained',
            '8 green olives, roughly chopped',
            '1 garlic clove, finely chopped',
            '1 tbsp olive oil',

            '2 tbsp chopped parsley, to serve']
    },
    {
        id: '18',
        categoryId: '4',
        name: 'Pitta pizzas',
        description: ['Heat oven to 200C/180C fan/gas 6 and put a baking sheet inside to heat up. Spread each pitta with 1 tsp purée. Top with the tomatoes, shallot, chorizo and cheddar.',

            'Place on the hot sheet and bake for 10 mins until the pittas are crisp, the cheese has melted and the chorizo has frazzled edges. Scatter with basil, if you like, and serve with a green salad.'],
        videoLink: '3pcv--uUVY8',
        image: '../img/pizza-3.jpg',
        author: 'Good Food',
        rating: '5',
        views: '822',
        ingredients: ['4 wholewheat pitta breads',
            '4 tsp sun-dried tomato purée',
            '3 ripe plum tomatoes, diced',
            '1 shallot, thinly sliced',
            '85g chorizo, diced',
            '50g mature cheddar, grated',
            'few basil leaves, if you like']
    },
    {
        id: '19',
        categoryId: '4',
        name: 'Rainbow pizzas',
        description: ['Heat the oven to 180C/160C fan/gas 4. Put each pizza base on a baking sheet and spread each with half of the passata. Arrange the tomatoes on the top in rings or wedges of colour and add the broccoli and the olives, if using. Squish the mozzarella cherries (bocconcini) a little before dotting them over the pizzas, then drizzle 1 tbsp pesto over each.',

            'Bake for 15-20 mins or until the top is bubbling and just starting to brown a little. Scatter over the basil leaves before serving.'],
        videoLink: 'NRsRZnGkB8M',
        image: '../img/pizza-4.jpg',
        author: 'Lulu Grimes',
        rating: '5',
        views: '386',
        ingredients: ['2 plain pizza bases',
            '6 tbsp passata',
            '400g mixed red and yellow tomatoes, sliced',
            '75g sprouting broccoli, stems finely sliced',
            '8 green olives, pitted and halved (optional)',
            '150g mozzarella cherries (bocconcini)',
            '2 tbsp fresh pesto',
            'handful fresh basil leaves, to serve']
    },
    {
        id: '20',
        categoryId: '4',
        name: 'Watermelon pizza',
        description: ['Take 1 round slice watermelon and cut into wedges, as you would a pizza, and lay them on a board. Scatter over 120g pineapple pieces, a few coriander or Thai basil leaves and 1-2 tsp toasted coconut flakes. Mix the juice ½ lime with 1 tbsp honey and drizzle over the top. Sprinkle with freshly cracked black pepper and zest ½ lime.'],
        videoLink: 'vzlRkmjfoG4',
        image: '../img/pizza-5.jpg',
        author: 'Miriam Nice',
        rating: '5',
        views: '841',
        ingredients: ['1 slice watermelon',
            '120g pineapple pieces',
            'a few coriander or Thai basil leaves',
            '1-2 tsp toasted coconut flakes',
            '½ lime (juice and zest)',
            '1 tbsp honey']
    },
    {
        id: '21',
        categoryId: '5',
        name: 'Creamy courgette & bacon pasta',
        description: ['Heat the olive oil in a large frying pan and sizzle the pancetta or bacon for about 5 mins until starting to crisp. Turn up the heat and add the grated courgette to the pan. Cook for 5 mins or until soft and starting to brown then add the garlic and cook for a minute longer. Season and set aside.',

            'Cook the tagliatelle according to the pack instructions and scoop out a cupful of cooking water. Drain the tagliatelle and tip into the frying pan with the bacon and courgette. Over a low heat toss everything together with the crème fraiche and half the Parmesan adding a splash of pasta water too if you need to loosen the sauce. Season to taste and serve twirled into bowls with the remaining Parmesan scattered over.'],
        videoLink: 'WVfVzeuek-M',
        image: '../img/pasta-1.jpg',
        author: 'Barney Desmazery',
        rating: '5',
        views: '384',
        ingredients: ['1 tsp olive oil',

            '150g diced pancetta or smoked bacon lardons',
            '4 courgettes, coarsely grated',
            '1 garlic clove, crushed',
            'handful freshly grated parmesan',

            '1 small tub (200g) low-fat crème fraîche',
            '300g tagliatelle']
    },
    {
        id: '22',
        categoryId: '5',
        name: 'Beef stroganoff with herby pasta',
        description: ['Freeze the beef for 45 mins before you begin, slice as thinly as you can, then season.',

            'In a large, non-stick frying pan, melt half the butter with half the oil. Increase the heat, then quickly sear the beef in batches until browned on both sides. Remove the meat and set aside. Repeat with the mushrooms, then set aside with the beef. Boil the pasta.',

            'Add the remaining butter and oil to the pan and soften the shallots for a few mins. Stir in the flour for 1 min, then gradually stir in the stock. Bubble for 5 mins until thickened, then stir in the mustard, purée, crème fraîche and seasoning. Bubble for 1 min more, then return the beef and mushrooms to the pan.',

            'Drain the pasta, toss with half the parsley, season, then serve with the creamy stroganoff, sprinkled with the remaining parsley.',

        ],
        videoLink: '2J482y8WVdo',
        image: '../img/pasta-2.jpg',
        author: 'Jennifer Joyce',
        rating: '5',
        views: '811',
        ingredients: ['400g beef rump steak, trimmed',
            '1 tbsp butter',

            '1 tbsp olive oil',

            '300g small button mushroom',
            '400g pappardelle pasta',
            '3 shallots, finely chopped',
            '1 tbsp plain flour',
            '300ml beef stock',
            '1 tbsp Dijon mustard',
            '1 tbsp tomato purée',
            '3 tbsp crème fraîche',
            '½ x 20g pack flat-leaf parsley, chopped']
    },
    {
        id: '23',
        categoryId: '5',
        name: 'Fresh pasta',
        description: ['Put the flour in a food processor with ¾ of your egg mixture and a pinch of salt. Blitz to large crumbs – they should come together to form a dough when squeezed (if it feels a little dry gradually add a bit more egg). Tip the dough onto a lightly floured surface, knead for 1 min or until nice and smooth – don’t worry if it’s quite firm as it will soften when it rests. Cover with cling film and leave to rest for 30 mins.',

            'Cut away ¼ of the dough (keep the rest covered with cling film) and feed it through the widest setting on your pasta machine. (If you don’t have a machine, use a heavy rolling pin to roll the dough as thinly as possible.) Then fold into three, give the dough a quarter turn and feed through the pasta machine again. Repeat this process once more then continue to pass the dough through the machine, progressively narrowing the rollers, one notch at a time, until you have a smooth sheet of pasta. On the narrowest setting, feed the sheet through twice.',

            'Cut as required to use for filled pastas like tortellini, or cut into lengths to make spaghetti, linguine, tagliatelle, or pappardelle. Then, dust in semolina flour and set aside, or hang until dry (an hour will be enough time.) Store in a sealed container in the fridge and use within a couple of days, or freeze for 1 month.'],
        videoLink: 'HdSLKZ6LN94',
        image: '../img/pasta-3.jpg',
        author: 'Elena Silcock',
        rating: '4',
        views: '528',
        ingredients: ['300g ‘00’ pasta flour, plus extra for dusting',
            '2 eggs and 4 yolks, lightly beaten',
            'semolina flour, for dusting']
    },
    {
        id: '24',
        categoryId: '5',
        name: 'Asparagus cream pasta',
        description: ['To prepare the asparagus, cut off and discard the woody ends, then neatly cut the tips away from the stalks. Keep the tips and stalks separate. In a small saucepan bring the cream and garlic to the boil. Take off the heat, remove the garlic, then set the pan aside.',

            'Cook the stalks in boiling salted water for about 4-5 mins until tender, drain, then tip into the cream with the grated parmesan. Blitz with a hand blender until smooth.',

            'Cook the pasta according to pack instructions, then throw in the tips 2 mins before the end of cooking time. Gently reheat the cream, drain pasta, then tip into a bowl with the cream. Toss, divide into pasta bowls, top with parmesan shavings and serve.'],
        videoLink: 'D9inRMjNFgQ',
        image: '../img/pasta-4.jpg',
        author: 'Barney Desmazery',
        rating: '5',
        views: '603',
        ingredients: ['1 bunch asparagus',
            '142ml tub double cream',
            '2 garlic cloves, peeled, but left whole',
            '50g parmesan, half grated, half shaved',
            '250g tagliatelle']
    },
    {
        id: '25',
        categoryId: '5',
        name: 'Saucy sausage pasta',
        description: ['Put a large pan of water on to boil. Heat the oil in a large frying pan and fry the sausage chunks on a fairly high heat until they are golden brown all over. Now turn the heat down and add the onion and garlic, cooking them until they have softened.',

            'Stir in the chilli powder and tomatoes with the sausages, bring the sauce to the boil then turn the heat down and let it bubble for about 10 minutes while you cook the pasta.',

            'Drop the pasta into the pan of boiling water and cook according to the pack instructions. Drain the pasta, then tip it into the frying pan with the sausage sauce, mixing well to coat. Dish up immediately with crusty bread.'],
        videoLink: 'rwDuK_R22BQ',
        image: '../img/pasta-5.jpg',
        author: 'Good Food',
        rating: '5',
        views: '495',
        ingredients: ['1 tbsp olive oil',

            'packet of 8 pork sausages (the best your budget will allow) cut into chunky pieces',
            '1 large onion, chopped',
            '2 garlic cloves, crushed',
            '1 tsp chilli powder',
            '400g can chopped tomatoes',
            '300g short pasta such as fusilli or farfalle (just over half a 500g bag)']
    }


]
