export default [
    {
        id: '1',
        categoryId: '1',
        name: 'Tavuklu Sultan Kebabı',
        description: ['Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın. Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.',
        'Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin. Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin. Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçapı ilave edin. Kapağını kapatarak 4-5dk kadar pişmeye bırakın. Suyunu çektikten sonra bezelye ve patlıcanı ilave edin. Baharatları da ekleyerek 3-4dk daha pişirin. Tavuklar da artık pişmiş olmalılar.'],
        videoLink: '-6IEwrzx2Nw',
        image: '../img/tavuklu-sultan-kebab-.jpg',
        author: 'Ana Yemek',
        rating: '4',
        views: '2515',
        ingredients:['2 adet yufka',
        '400g tavuk göğsü',
        '400g tavuk pirzola']
    },
    {
        id: '2',
        categoryId: '1',
        name: 'Tavuklu Sultan Kebabı',
        description: ['Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın. Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.',
            'Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin. Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin. Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçapı ilave edin. Kapağını kapatarak 4-5dk kadar pişmeye bırakın. Suyunu çektikten sonra bezelye ve patlıcanı ilave edin. Baharatları da ekleyerek 3-4dk daha pişirin. Tavuklar da artık pişmiş olmalılar.'],
        videoLink: '-6IEwrzx2Nw',
        image: '../img/tavuklu-sultan-kebab-.jpg',
        author: 'Ana Yemek',
        rating: '4',
        views: '2515',
        ingredients:['2 adet yufka',
            '400g tavuk göğsü',
            '400g tavuk pirzola']
    },
    {
        id: '3',
        categoryId: '1',
        name: 'test',
        description: ['Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın. Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.',
            'Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin. Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin. Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçapı ilave edin. Kapağını kapatarak 4-5dk kadar pişmeye bırakın. Suyunu çektikten sonra bezelye ve patlıcanı ilave edin. Baharatları da ekleyerek 3-4dk daha pişirin. Tavuklar da artık pişmiş olmalılar.'],
        videoLink: '-6IEwrzx2Nw',
        image: '../img/tavuklu-sultan-kebab-.jpg',
        author: 'Ana Yemek',
        rating: '4',
        views: '2515',
        ingredients:['2 adet yufka',
            '400g tavuk göğsü',
            '400g tavuk pirzola']
    },
    {
        id: '4',
        categoryId: '1',
        name: 'Tavuklu Sultan Kebabı',
        description: ['Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın. Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.',
            'Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin. Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin. Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçapı ilave edin. Kapağını kapatarak 4-5dk kadar pişmeye bırakın. Suyunu çektikten sonra bezelye ve patlıcanı ilave edin. Baharatları da ekleyerek 3-4dk daha pişirin. Tavuklar da artık pişmiş olmalılar.'],
        videoLink: '-6IEwrzx2Nw',
        image: '../img/tavuklu-sultan-kebab-.jpg',
        author: 'Ana Yemek',
        rating: '4',
        views: '2515',
        ingredients:['2 adet yufka',
            '400g tavuk göğsü',
            '400g tavuk pirzola']
    },
    {
        id: '5',
        categoryId: '1',
        name: 'Tavuklu Sultan Kebabı',
        description: ['Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın. Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.',
            'Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin. Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin. Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçapı ilave edin. Kapağını kapatarak 4-5dk kadar pişmeye bırakın. Suyunu çektikten sonra bezelye ve patlıcanı ilave edin. Baharatları da ekleyerek 3-4dk daha pişirin. Tavuklar da artık pişmiş olmalılar.'],
        videoLink: '-6IEwrzx2Nw',
        image: '../img/tavuklu-sultan-kebab-.jpg',
        author: 'Ana Yemek',
        rating: '4',
        views: '2515',
        ingredients:['2 adet yufka',
            '400g tavuk göğsü',
            '400g tavuk pirzola']
    },
    {
        id: '6',
        categoryId: '2',
        name: 'test 2',
        description: ['Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın. Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.',
            'Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin. Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin. Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçapı ilave edin. Kapağını kapatarak 4-5dk kadar pişmeye bırakın. Suyunu çektikten sonra bezelye ve patlıcanı ilave edin. Baharatları da ekleyerek 3-4dk daha pişirin. Tavuklar da artık pişmiş olmalılar.'],
        videoLink: '-6IEwrzx2Nw',
        image: '../img/tavuklu-sultan-kebab-.jpg',
        author: 'Ana Yemek',
        rating: '4',
        views: '2515',
        ingredients:['2 adet yufka',
            '400g tavuk göğsü',
            '400g tavuk pirzola']
    }
]
