export const FETCH_DISHES_START = 'FETCH_DISHES_START';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const FETCH_DISHES_FAILURE = 'FETCH_DISHES_FAILURE';

export const FETCH_DISHBYID_START = 'FETCH_DISHBYID_START';
export const FETCH_DISHBYID_SUCCESS = 'FETCH_DISHBYID_SUCCESS';
export const FETCH_DISHBYID_FAILURE = 'FETCH_DISHBYID_FAILURE';
